### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by sansin** [arvinsingla/rfswitcher#1]
See error below.

`events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1023:19)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at EventEmitter.listen (/xxxx/rfswitcher/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/xxxx/rfswitcher/switcher.js:41:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)`

**Comment by oskargert** [comment]
I too have some problems on getting it started..

My error code:

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1237:19)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1382:5)
    at EventEmitter.listen (/home/pi/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/pi/switcher.js:41:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by sansin** [comment]
I got it resolved by changing port in config file. This error occurs when port is occupied. 

Try changing port and start again.

**Comment by oskargert** [comment]
Thanks! I might have gotten it to work. At least the error is gone. Now my problem is that in my config.json i don have a status_url, and homebridge is complaining over this and refuses to send my requests. 

What would my status url be?

this is my config.json

{
     "bridge": {
        "name": "HomeBridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

```
"description": "HomeBridge HTTP Status Control",

"accessories": [ {
        "accessory": "Http",
            "name": "sänglampan",
        "switchHandling": "yes",
            "http_method": "GET",
            "on_url":      "http://localhost/api/switch/5246997",
            "off_url":     "http://localhost/api/switch/5246996",
            "status_url": "",               
                "service": "Light",
            "brightnessHandling": "no",
            "brightness_url":     "",
            "brightnesslvl_url":  ""            

   } 
]
```

}

**Comment by sansin** [comment]
I've built my own application for API and I have status URL so it works. But in your case here if you do not have a separate status URL, you can give any valid URL. 

try this http://localhost/api/switch

Status on the Homekit app will not be accurate but atleast it works.
